### ISSUE TITLE
Consider adding support for argon2

### ISSUE THREAD

**Issue by postmodern** [sebastjan-hribar/tachiban#15]
[Bcrypt will eventually be phased out](https://www.wired.com/story/bcrypt-password-hashing-25-years/). Many people are slowly adopting [Argon2](https://www.educative.io/answers/what-is-the-argon2-function), which provides increased protection against password cracking. There is also a [argon2](https://rubygems.org/gems/argon2) gem which provides FFI bindings to `libargon2`; see example usage [here](https://github.com/katafrakt/palaver/blob/3b9c814c0273845d23f7708a12e5cbe102240574/slices/account/commands/sign_in.rb#L16).

**Comment by sebastjan-hribar** [comment]
1.0 now supports only Argon2. 0.8 still supports BCrypt.
